//! Native Rust bindings to the Everything-SDK
#![cfg(windows)]

// use manual bindings instead of automatically generated by rust-bindgen
mod bindings;
pub use bindings::*;

#[cfg(not(feature = "vendored"))]
#[allow(non_snake_case)]
mod dummy_msi {
    use bindings::UINT;

    pub unsafe fn Everything_MSIExitAndStopService(_msihandle: *const std::ffi::c_void) -> UINT {
        1 // dummy function always fails
    }

    pub unsafe fn Everything_MSIStartService(_msihandle: *const std::ffi::c_void) -> UINT {
        1 // dummy function always fails
    }
}

#[cfg(not(feature = "vendored"))]
pub use dummy_msi::*;
